### ISSUE TITLE
User model modifications + Pet Model

### ISSUE THREAD

**Issue by skassam21** [hatchways/team-panda#17]
- User model
  - Created_at timestamp (auto adding it)
  - Location - String
  - overview/about 
  - Introduction
  - profile_pic
- Pet model - Edson
  - Needs a one to many relationships with users 
  - Some other data

**Comment by Edsonzhu** [comment]
@skassam21 the "Created_at" is when profile was created or when the user has his first pet?

**Comment by Edsonzhu** [comment]
@skassam21 , I accidentaly merged the models to the dev source instead of creating a pr, what should i do?
